name: GitHub Metrics Professional
on:
  schedule:
    - cron: "0 0 * * *" # Execução diária à meia-noite
  workflow_dispatch: # Permite que você execute manualmente para testar agora
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: General Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: tarcisoferreiradev
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugin de Medalhas (Achievements)
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # Análise de Stack (Alinhado ao projeto Alimentando Fases)
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used